package com.carrera.carreraCaballos.modelos;

import javax.swing.*;
import java.awt.*;
import java.util.Observable;
import java.util.Observer;

public class FrmCarrera extends javax.swing.JFrame implements Observer {

    private Thread[] hilos;
    // Inicializamos por defecto a 8, en caso de que el usuario no introduzca ningún número
    private int numHilos = 8;


    public FrmCarrera() {
        initComponents();
        hilos = new Thread[numHilos];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pg1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        pg2 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        pg3 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        pg4 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pg5 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        pg6 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        pg7 = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        pg8 = new javax.swing.JProgressBar();
        lblGanador = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        SpinnerNumberModel model1 = new SpinnerNumberModel(1, 1, 8, 1);
        spinner1 = new javax.swing.JSpinner(model1);


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);



        numLabel.setText("Nº de caballos: (1-8)");

        pg1.setStringPainted(true);

        jLabel1.setText("Caballo 1");

        pg2.setStringPainted(true);

        jLabel2.setText("Caballo 2");

        pg3.setStringPainted(true);

        jLabel3.setText("Caballo 3");

        pg4.setStringPainted(true);

        jLabel4.setText("Caballo 4");
        pg5.setStringPainted(true);

        jLabel5.setText("Caballo 5");

        pg6.setStringPainted(true);

        jLabel6.setText("Caballo 6");

        pg7.setStringPainted(true);

        jLabel7.setText("Caballo 7");

        pg8.setStringPainted(true);

        jLabel8.setText("Caballo 8");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel9.setText("El ganador es: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        int pref = 533;
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(pg1, javax.swing.GroupLayout.PREFERRED_SIZE, pref, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(pg2, javax.swing.GroupLayout.PREFERRED_SIZE, pref, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(pg3, javax.swing.GroupLayout.PREFERRED_SIZE, pref, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(pg4, javax.swing.GroupLayout.PREFERRED_SIZE, pref, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(pg5, javax.swing.GroupLayout.PREFERRED_SIZE, pref, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(pg6, javax.swing.GroupLayout.PREFERRED_SIZE, pref, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(pg7, javax.swing.GroupLayout.PREFERRED_SIZE, pref, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(pg8, javax.swing.GroupLayout.PREFERRED_SIZE, pref, javax.swing.GroupLayout.PREFERRED_SIZE))

                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(numLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))

                                        )

                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(225, 225, 225)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(19, Short.MAX_VALUE))
        );
        int pref1 = 25;
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel1))
                                        .addComponent(pg1, javax.swing.GroupLayout.PREFERRED_SIZE, pref1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel2))
                                        .addComponent(pg2, javax.swing.GroupLayout.PREFERRED_SIZE, pref1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel3))
                                        .addComponent(pg3, javax.swing.GroupLayout.PREFERRED_SIZE, pref1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel4))
                                        .addComponent(pg4, javax.swing.GroupLayout.PREFERRED_SIZE, pref1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel5))
                                        .addComponent(pg5, javax.swing.GroupLayout.PREFERRED_SIZE, pref1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel6))
                                        .addComponent(pg6, javax.swing.GroupLayout.PREFERRED_SIZE, pref1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel7))
                                        .addComponent(pg7, javax.swing.GroupLayout.PREFERRED_SIZE, pref1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel8))
                                        .addComponent(pg8, javax.swing.GroupLayout.PREFERRED_SIZE, pref1, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblGanador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)

                                )


                                .addGap(34, 34, 34)

                        )

        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        numHilos = (int) spinner1.getValue();


        this.btnIniciar.setEnabled(false);
        this.lblGanador.setText("");

        for (int i = 0; i < numHilos; i++) {
            Caballo c = new Caballo((i + 1) + "");
            c.addObserver(this);
            hilos[i] = new Thread(c);
            hilos[i].start();
        }


    }//GEN-LAST:event_btnIniciarActionPerformed

    private void terminar() {

        for (int i = 0; i < numHilos; i++) {
            hilos[i].interrupt();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void lanzador(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCarrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblGanador;
    private javax.swing.JProgressBar pg1;
    private javax.swing.JProgressBar pg2;
    private javax.swing.JProgressBar pg3;
    private javax.swing.JProgressBar pg4;
    private JProgressBar pg5;
    private JProgressBar pg6;
    private JLabel jLabel6;
    private JProgressBar pg7;
    private JLabel jLabel7;
    private JProgressBar pg8;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JLabel numLabel;
    private JSpinner spinner1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {

        Caballo c = (Caballo) o;
        int porcentaje = (int) arg;

        switch (c.getNombre()) {
            case "1":
                this.pg1.setValue(porcentaje);
                break;

            case "2":
                this.pg2.setValue(porcentaje);
                break;

            case "3":
                this.pg3.setValue(porcentaje);
                break;

            case "4":
                this.pg4.setValue(porcentaje);
                break;
            case "5":
                this.pg5.setValue(porcentaje);
                break;

            case "6":
                this.pg6.setValue(porcentaje);
                break;

            case "7":
                this.pg7.setValue(porcentaje);
                break;

            case "8":
                this.pg8.setValue(porcentaje);
                break;

        }

        if (porcentaje >= 100) {
            terminar();
            this.btnIniciar.setEnabled(true);
            this.lblGanador.setText("Caballo " + c.getNombre());
        }


    }



}


